spring:
 application:
  name: gateway-lb-demo
  
#either this configuration for routes or the java configuration
 cloud:
  gateway:
   discovery:
    locator:
     enabled: true
#   routes:
#    - id: lb-service1
#      uri: lb://lb-service1 
#      predicates :
#       - Path=/service1/**
  
      
    
     
    
    

management:
 endpoints:
  web:
   exposure:
    include: "*"
 endpoint: 
  health:
    show-details: always
  gateway:
   enabled: true
   
server:
 port: 8070